# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Linux test and SNAPSHOT deploy with Maven

on:
  push:
    branches: [ master, highprecision, development ]
  pull_request:
    branches: [ master, highprecision ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Test and package with Maven
      run: mvn clean package

      
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/development'
    needs: build
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Configure deploy for snapshots
          run: echo "SERVER_ID=vdmj.overture.au.dk-snapshots" >> $GITHUB_ENV
        - name: Environment variables
          run: echo ${{ env.SERVER_ID }}
        - name: Set up JDK
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Deploy
          run: mvn -B deploy
          env:
            MAVEN_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
            MAVEN_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
