# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Linux test and SNAPSHOT deploy with Maven

on:
  push:
    branches: [ master, highprecision, development ]
  pull_request:
    branches: [ master, highprecision ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Test and package with Maven
      run: mvn test

  deploy:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
        - name: Getting POM version
          run: echo "POM_VERSION=$(mvn -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_ENV
        - name: Checking out  
          uses: actions/checkout@v2
        - name: Configure deploy for snapshots
          run: echo "SERVER_ID=vdmj.overture.au.dk-snapshots" >> $GITHUB_ENV
        - name: Check variables
          run: |
            echo ${{ env.SERVER_ID }}
            echo ${{ env.POM_VERSION }}
        - name: Set up JDK
          if: contains(${{ env.POM_VERSION }}, "SNAPSHOT" )
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
            server-id: ${{ env.SERVER_ID }}
            server-username: MAVEN_USERNAME
            server-password: MAVEN_PASSWORD
        - name: Deploy
          if: contains(${{ env.POM_VERSION }}, "SNAPSHOT" )
          run: mvn -B deploy
          env:
            MAVEN_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
            MAVEN_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
